# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create Release

on:
  push:
    tags: 
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: tag and prepare release
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: preparations
      run: |
        npm i
        npm ci
    - name: prepare models
      run: |
        cd models
        npm i
        npm ci
    - name: prepare backend
      run: |
        cd backend
        npm i
        npm ci
    - name: prepare frontend
      run: |
        cd frontend
        npm i
        npm ci
    - name: package
      run: |
        gulp
    - name: create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
        create_draft: false
        update_existing: true
    - name: upload artifacts to release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: f1-telemetry-win.exe
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}